# Generated by Django 2.0.3 on 2018-04-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='anketa',
            name='question',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study_material',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
    ]
