# Generated by Django 2.0.3 on 2018-03-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180327_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
