# Generated by Django 2.0.3 on 2018-03-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180329_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='image/user_deafult/user', upload_to=''),
        ),
    ]
