# Generated by Django 2.0.3 on 2018-03-27 17:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180327_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='/media/pictures')),
        ),
    ]
