# Generated by Django 2.0.3 on 2018-03-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180329_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='static/images/user_default/user.png', upload_to=''),
        ),
    ]
